services:
  customer:
      container_name: customer-dotnet
      build:
          dockerfile: Source/Dockerfile
      image: customers-core:latest
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
          - 5244:8080
      networks:
          - pfcti-network-dotnet
  postgres:
      container_name: postgres-dotnet
      image: postgres:16.3-alpine
      hostname: postgres
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
        - ~/apps/postgres:/var/lib/postgresql@16/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - PGPORT=${POSTGRES_PORT}
      networks:
          - pfcti-network-dotnet
networks:
    pfcti-network-dotnet:
        driver: bridge